// Generated by gencpp from file ros_tutorial/Cylinder.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MESSAGE_CYLINDER_H
#define ROS_TUTORIAL_MESSAGE_CYLINDER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorial
{
template <class ContainerAllocator>
struct Cylinder_
{
  typedef Cylinder_<ContainerAllocator> Type;

  Cylinder_()
    : volume(0.0)
    , surface_area(0.0)  {
    }
  Cylinder_(const ContainerAllocator& _alloc)
    : volume(0.0)
    , surface_area(0.0)  {
  (void)_alloc;
    }



   typedef double _volume_type;
  _volume_type volume;

   typedef double _surface_area_type;
  _surface_area_type surface_area;





  typedef boost::shared_ptr< ::ros_tutorial::Cylinder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorial::Cylinder_<ContainerAllocator> const> ConstPtr;

}; // struct Cylinder_

typedef ::ros_tutorial::Cylinder_<std::allocator<void> > Cylinder;

typedef boost::shared_ptr< ::ros_tutorial::Cylinder > CylinderPtr;
typedef boost::shared_ptr< ::ros_tutorial::Cylinder const> CylinderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorial::Cylinder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorial::Cylinder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tutorial::Cylinder_<ContainerAllocator1> & lhs, const ::ros_tutorial::Cylinder_<ContainerAllocator2> & rhs)
{
  return lhs.volume == rhs.volume &&
    lhs.surface_area == rhs.surface_area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tutorial::Cylinder_<ContainerAllocator1> & lhs, const ::ros_tutorial::Cylinder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::Cylinder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial::Cylinder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::Cylinder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial::Cylinder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::Cylinder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial::Cylinder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorial::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d4d85be24438773cbf4abab3bea881b";
  }

  static const char* value(const ::ros_tutorial::Cylinder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d4d85be24438773ULL;
  static const uint64_t static_value2 = 0xcbf4abab3bea881bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorial::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorial/Cylinder";
  }

  static const char* value(const ::ros_tutorial::Cylinder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorial::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 volume		#Parameter for number volume\n"
"float64 surface_area	#Parameter for value surface area\n"
"\n"
;
  }

  static const char* value(const ::ros_tutorial::Cylinder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorial::Cylinder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.volume);
      stream.next(m.surface_area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cylinder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorial::Cylinder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorial::Cylinder_<ContainerAllocator>& v)
  {
    s << indent << "volume: ";
    Printer<double>::stream(s, indent + "  ", v.volume);
    s << indent << "surface_area: ";
    Printer<double>::stream(s, indent + "  ", v.surface_area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIAL_MESSAGE_CYLINDER_H
